# Criei esse manifest para utilizar uma imagem inexistente de maneira proposital
apiVersion: v1
kind: Pod
metadata:
  name: broken-pod
  labels:
    app: broken-image
    environment: staging
    author: eumirandarainer
spec:
  containers:
  - name: broken-app 
    image: eumirandarainer/my-inexistent-image

# Para observar os eventos do Pod:
# kubectl events --for pod/broken-pod
