apiVersion: v1
kind: Pod
metadata:
  name: busy-pod
  labels:
    app: busybox
    terminal: active
spec:
  containers:
  - name: busybox
    image: busybox:1.28 
    command: ['sleep','3600'] 

# kubectl exec -it busy-pod -- /bin/sh
