# Sample pod
apiVersion: v1
kind: Pod
metadata:
  name: sample-app-pod
  labels:
    app: sample-app
    environment: staging
    author: eumirandarainer
spec:
  containers:
  - name: sample-app
    image: eumirandarainer/sample-app
    ports:
    - containerPort: 8888


# Habilitar o port-foward para conseguir fazer requisicoes locais
