# Sample pod
apiVersion: v1
kind: Pod
metadata:
  name: simple-go-app-pod
  labels:
    app: simple-go-app
    environment: staging
    author: eumirandarainer
spec:
  containers:
  - name: simple-go-app-ctr
    image: eumirandarainer/simple-go-app
    ports:
    - containerPort: 8888


# Habilitar o port-foward para conseguir fazer requisicoes locais
