apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-go-app-deploy
  labels:
    author: eumirandarainer
    strategy: "yes"
spec:
  replicas: 5
  selector:
    matchLabels:
      app: simple-go-app
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: simple-go-app
    spec:
      containers:
      - name: simple-go-app-ctr
        image: eumirandarainer/simple-go-app
        ports:
        - containerPort: 8888
