apiVersion: v1
kind: Service
metadata:
  name: simple-go-app-svc-cip
  labels:
    app: simple-go-app
spec:
  type: ClusterIP
  ports:
  - port: 8888
    targetPort: 8888
    protocol: TCP
  selector:
    app: simple-go-app
