apiVersion: v1
kind: Service
metadata:
  name: sample-app-svc-cip
  labels:
    app: sample-app
spec:
  type: ClusterIP
  ports:
  - port: 8888
    targetPort: 8888
    protocol: TCP
  selector:
    app: sample-app
