apiVersion: v1
kind: Service
metadata:
  name: simple-go-app-svc-np
  labels:
    app: simple-go-app
spec:
  type: NodePort
  ports:
  - port: 8888
    nodePort: 30001
    protocol: TCP
  selector:
    app: simple-go-app
