apiVersion: v1
kind: Service
metadata:
  name: sample-app-svc
  labels:
    app: sample-app
spec:
  type: NodePort
  ports:
  - port: 8888
    nodePort: 30001
    protocol: TCP
  selector:
    app: sample-app
